// toffy-console.app.cpp
#include <iostream>
#include <string>
#include "toffy.h"  // Include the Toffy header file

int main() {
    Toffy toffy;  // Create an instance of the Toffy chatbot
    std::string user_input;
    std::string user_name = "Sandip";  // User's name

    // Greeting generated by the bot
    std::cout << "Toffy: " << toffy.greet(user_name) << std::endl;

    while (true) {
        std::cout << "You: ";
        std::getline(std::cin, user_input);  // Get user input

        // If user types "bye", end the conversation
        if (user_input == "bye") {
            std::cout << "Toffy: Goodbye " << user_name << "! See you next time!" << std::endl;
            break;
        }

        // Get the chatbot's response and output it
        std::cout << "Toffy: " << toffy.process(user_input, user_name) << std::endl;
    }

    return 0;
}
